
version: 2

models:
  - name: DIMCUSTOMER
    description: "Dimension Table to load Customer data"
    columns:
      - name: CUSTOMERSOURCEKEY 
        description: "The primary key for this table"
        tests:
          - unique
          

  - name: DIMPRODUCT
    description: "Dimension Table to load Customer data"
    columns:
      - name: ProductSourceKey
        description: "The primary key for this table"
        tests:
          - unique
          
   
  - name: DIMCAMPAIGN
    description: "Dimension Table to load Campaign data"
    columns:
      - name: CampaignSourceKey
        description: "The primary key for this table"
        tests:
          - unique
          

  - name: FACTSALES
    description: "Fact Sales Table to load the Sales Data"
    columns:
      - name: CUSTOMERID 
        description: "The primary key for this table"
        tests:
          - unique
          

            
           