
version: 2

models:
  - name: DIM_CUSTOMER
    description: "Dimension Table to load Customer data"
    columns:
      - name: CUSTOMERSOURCEKEY 
        description: "The primary key for this table"
        tests:
          - unique
          

  - name: DIM_PRODUCT
    description: "Dimension Table to load Customer data"
    columns:
      - name: ProductSourceKey
        description: "The primary key for this table"
        tests:
          - unique
          
   
  - name: DIM_CAMPAIGN
    description: "Dimension Table to load Campaign data"
    columns:
      - name: CampaignSourceKey
        description: "The primary key for this table"
        tests:
          - unique
          

  - name: FACT_SALES
    description: "Fact Sales Table to load the Sales Data"
    columns:
      - name: CUSTOMERID 
        description: "The primary key for this table"
        tests:
          - unique
          

            
           