insert into "DATA_TO_INSIGHTS"."DATA_TO_INSIGHTS_TRAINING"."DIMCUSTOMER"
(
CUSTOMERID,  
CUSTOMERSOURCEKEY	,
CUSTOMERNAME	,
ADDRESS	,
CREATEDDATE	,
CREATEDBY	,
MODIFIEDDATE	,
MODIFIEDBY )

select 

seq1.nextval as CUSTOMER_ID,
CUSTOMER_ID as CUSTOMERSOURCEKEY,
CUSTOMER_NAME as CUSTOMERNAME,
concat(CITY,',',STATE,',',COUNTRY,',',REGION,',',POSTAL_CODE) as ADDRESS,
sysdate() as CREATEDDATE	,
'fivetran' as CREATEDBY	,
sysdate() MODIFIEDDATE	,
'fivetran' MODIFIEDBY from "DATA_TO_INSIGHTS"."GOOGLE_DRIVE"."CUSTOMER_COMPLETE"
where CUSTOMER_ID not in (select distinct CUSTOMERSOURCEKEY from "DATA_TO_INSIGHTS"."DATA_TO_INSIGHTS_TRAINING"."DIMCUSTOMER")
;